apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rliph73za-go
  janus-idp.io/tekton: rliph73za-go
  backstage.io/kubernetes-id: rliph73za-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rliph73za-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
